<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ANHROG" ignored="0" name="Test 2" tests="5" failures="2" timestamp="09 Aug 2017 04:02:10 GMT" time="0.018" errors="0">
  <testcase name="testMethod1" time="0.003" classname="testclasses.TestAnnotationTest"/>
  <testcase name="testMethod2" time="0.001" classname="testclasses.TestAnnotationTest"/>
  <testcase name="testMethod3" time="0.001" classname="testclasses.TestAnnotationTest">
    <failure type="java.lang.AssertionError" message=" expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError:  expected [3] but found [4]
	at testclasses.TestAnnotationTest.testMethod3(TestAnnotationTest.java:36)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testmethod4" time="0.003" classname="testclasses.TestAnnotationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [10] but found [20]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [10] but found [20]
	at testclasses.TestAnnotationTest.testmethod4(TestAnnotationTest.java:50)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testmethod4 -->
  <testcase name="testmethod5" time="0.0" classname="testclasses.TestAnnotationTest"/>
</testsuite> <!-- Test 2 -->
